sudo: required
services:
    - docker

before_install:
    - docker build -t jasmin.virdi/docker-github-action-application -f Dockerfile.dev .

script:
    - docker run jasmin.virdi/docker-github-action-application npm run test -- --coverage 