sudo: required
services:
    - docker

before_install:
    - docker build -t jasminvirdi/docker-github-action-application -f Dockerfile.dev .

script:
    - docker run jasminvirdi/docker-github-action-application npm run test -- --coverage 