sudo: required
services:
    - docker

before_install:
    - docker build -t jasminvirdi/docker-github-action-application -f Dockerfile.dev .

script:
    - docker run jasminvirdi/docker-github-action-application npm run test -- --coverage 

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-3064766327547"
    bucket_path: "docker"
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
            secure: "$AWS_SECRET_KEY"

